#!/usr/bin/env node

import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

// Read package.json
const packageJsonPath = join(import.meta.dirname, "..", "package.json");
const packageJson = JSON.parse(readFileSync(packageJsonPath, "utf-8")) as {
    version: string;
    engines?: { node?: string };
};

const nodeEngine = packageJson.engines?.node ?? ">=20.0.0";

// Define the packageInfo.ts content
const packageInfoContent = `// This file was generated by scripts/updatePackageVersion.ts - Do not edit it manually.
export const packageInfo: {
    version: string;
    mcpServerName: string;
    engines: { node: string };
} = {
    version: "${packageJson.version}",
    mcpServerName: "MongoDB MCP Server",
    engines: {
        node: "${nodeEngine}",
    },
};
`;

// Write to packageInfo.ts
const packageInfoPath = join(import.meta.dirname, "..", "src", "common", "packageInfo.ts");
writeFileSync(packageInfoPath, packageInfoContent);

// Keep the .mcpb manifest's version in lockstep with package.json.
const manifestPath = join(import.meta.dirname, "..", "packaging", "mcpb", "manifest.json");
const manifest = JSON.parse(readFileSync(manifestPath, "utf-8")) as { version: string };
manifest.version = packageJson.version;
writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + "\n");
